version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: storage
    volumes:
      - /Users/sterlu/Dev/RS2-IS-Pozoriste/data:/data/db
    ports:
      - 27017:27017
  payment:
    build: ./PaymentService/
    container_name: payment
    depends_on:
      - mongodb
  server:
    build: ./Server/
    container_name: server
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - payment
